# .scss-lint.yml

# inherit_from: ''
# exclude: ''

linters:
    Comment:
        enabled: false
    HexNotation:
        style: lowercase
    ImportPath:
        leading_underscore: false
        filename_extension: false
    Indentation:
        exclude:
            - 'plugins/**'
        severity: warning
        character: tab
        width: 1
    LeadingZero:
        style: include_zero
    NameFormat:
        convention: hyphenated_lowercase
    PropertySortOrder:
        enabled: false
    SelectorFormat:
        convention: hyphenated_BEM
    Shorthand:
        enabled: true
    SpaceAfterPropertyColon:
        style: at_least_one_space
    SpaceBeforeBrace:
        allow_single_line_padding: true
    StringQuotes:
        style: single_quotes
    UrlQuotes:
        enabled: false
    VendorPrefix:
        enabled: false